### ISSUE TITLE
Echoing messages on stdout should be an info level log, not error

### ISSUE THREAD

**Issue by awused** [xenova/chat-replay-downloader#52] opened 2021-01-31 11:11 UTC
`--logging warning` and `--logging error` should disable printing messages to stdout. Right now only `--logging none` disables this, so it's impossible to log errors without logging all messages.

**Comment by xenova** [comment] 2021-01-31 11:50
I thought the intended behaviour of the `logging` library (https://docs.python.org/3/library/logging.html) was to set messages at a hierarchical level?

From the [docs](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel):
> Sets the threshold for this logger to level. Logging messages which are less severe than level will be ignored; logging messages which have severity level or higher will be emitted by whichever handler or handlers service this logger, unless a handler’s level has been set to a higher severity level than level.
> 
> When a logger is created, the level is set to NOTSET (which causes all messages to be processed when the logger is the root logger, or delegation to the parent when the logger is a non-root logger). Note that the root logger is created with level WARNING.


If I am not mistaken, error and warning messages are sent to stderr, are they not? So you can split up the output streams with output redirection?

So, for example, 
`chat_replay_downloader --logging error https://www.youtube.com/watch?v=J2umj9SgdFU 2> stderr.txt > stdout.txt`

would output the following two files:
[stderr.txt](https://github.com/xenova/chat-replay-downloader/files/5899635/stderr.txt)
[stdout.txt](https://github.com/xenova/chat-replay-downloader/files/5899636/stdout.txt)

**Comment by awused** [comment] 2021-01-31 12:36
I was using it interactively and not splitting out stderr, that does work. But it was very jarring to go from the previous version with `--hide_output` to this version with `--logging warning` and still have all messages echoed. I'm not sure why the `--logging` parameter affects message echoing, or why they're counted at the same level of criticality as errors, if the intended solution is to use redirection in place of cli options.

**Comment by xenova** [comment] 2021-02-01 17:09
> I was using it interactively and not splitting out stderr, that does work. But it was very jarring to go from the previous version with `--hide_output` to this version with `--logging warning` and still have all messages echoed. I'm not sure why the `--logging` parameter affects message echoing, or why they're counted at the same level of criticality as errors, if the intended solution is to use redirection in place of cli options.

The main reason I added logging functionality was to assist in debugging, so I just implemented it in the standard way (according to the docs). If your aim is to output to a file, you can just use the `--output` option.

**Comment by awused** [comment] 2021-02-02 03:22
You seem to be misunderstanding something. I am using `--output` to produce a json file. Previously I'd used `--hide_output` since echoing messages on stdout was annoying and useless to me. The `--hide_output` parameter was removed and `--logging` was the obvious replacement. I tried to replicate the same behaviour with `--logging` and found only `--logging none` hid the messages.

It makes little sense that `--logging` affects echoing messages to stdout if the intended solution is to redirect stdout to /dev/null, and if `--logging` is supposed to affect messages it makes little sense that they're treated with the same criticality as errors.

**Comment by xenova** [comment] 2021-02-02 05:13
Okay I think I understand now. So, do you suggest I add the `--hide_output` flag back? This will ensure that nothing is printed at all. On the other hand, setting logging to none will only show the chat messages (i.e. no info, warning, error or critical messages.)


Or what should I change?

**Comment by awused** [comment] 2021-02-02 12:06
Yeah, it's better if it behaves consistently. A `--hide_output` or `--quiet` parameter is nice to have, but even without that at least `--logging` shouldn't affect the chat messages which was what surprised me and led to this bug report.

**Comment by xenova** [comment] 2021-02-02 12:15
Sounds good 👍 I will close this issue once it has been added. Thanks for the suggestion!

**Closed** 2021-02-02 12:50 UTC

**Comment by xenova** [comment] 2021-02-02 12:51
@awused That should fix it 👍 ... if there is still an error, feel free to leave another comment.
